version: '3'

services:
  react-app:
    image: cv-geneartor-react
    container_name: cv-geneartor
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:80"
    networks:
      - devops_front
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok-container
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
    networks:
      - devops_front
networks:
  devops_front:
    external:
      name: devops_api